apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ticketing-secrets
  namespace: ticketing
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: ticketing-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_WRITER_HOST
      remoteRef:
        key: {{ .Values.externalSecret.dbWriterHostKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: DB_READER_HOST
      remoteRef:
        key: {{ .Values.externalSecret.dbReaderHostKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecret.dbUserKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.dbPasswordKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ELASTICACHE_PRIMARY_ENDPOINT
      remoteRef:
        key: {{ .Values.externalSecret.elasticachePrimaryEndpointKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: REDIS_HOST
      remoteRef:
        key: {{ .Values.externalSecret.redisHostKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
