apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ticketing-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: ticketing-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_WRITER_HOST
      remoteRef:
        # AWS Parameter Store에서 키 이름을 참조하여 값을 가져옴
        key: {{ .Values.externalSecret.dbWriterHostKey }}
        # conversionStrategy: 가져온 값을 Kubernetes Secret에 저장하기 전에 변환하는 방법을 지정
        conversionStrategy: Default
        # decodingStrategy: 가져온 값이 인코딩된 경우 이를 디코딩하는 방법을 지정
        decodingStrategy: None
        # metadataPolicy: 데이터의 값만 가져오고, 메타데이터는 무시하도록 설정
        metadataPolicy: None
    - secretKey: DB_READER_HOST
      remoteRef:
        key: {{ .Values.externalSecret.dbReaderHostKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.externalSecret.dbUserKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.dbPasswordKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ELASTICACHE_PRIMARY_ENDPOINT
      remoteRef:
        key: {{ .Values.externalSecret.elasticachePrimaryEndpointKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: REDIS_HOST
      remoteRef:
        key: {{ .Values.externalSecret.redisHostKey }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
