{{- range $name, $svc := .Values.services }}
{{- if and $svc.keda $svc.keda.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $name }}-sqs
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
  {{- if $svc.keda.paused }}
  annotations:
    autoscaling.keda.sh/paused: "true"
  {{- end }}
spec:
  scaleTargetRef:
    name: {{ $name }}
  pollingInterval: {{ $svc.keda.pollingInterval }}
  cooldownPeriod: {{ $svc.keda.cooldownPeriod }}
  minReplicaCount: {{ $svc.keda.minReplicas }}
  maxReplicaCount: {{ $svc.keda.maxReplicas }}
  {{- with $svc.keda.scaleDownStabilizationWindowSeconds }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ . }}
  {{- end }}
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: {{ $.Values.keda.triggerAuthentication.name }}
      metadata:
        awsRegion: {{ $.Values.config.AWS_REGION }}
        queueURLFromEnv: {{ $svc.keda.sqsQueueEnvVar }}
        queueLength: {{ $svc.keda.queueLength | quote }}
        {{- with $svc.keda.activationQueueLength }}
        activationQueueLength: {{ . | quote }}
        {{- end }}
        {{- if $svc.keda.scaleOnInFlight }}
        scaleOnInFlight: "true"
        {{- end }}
{{- end }}
{{- end }}
