apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: write-api-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: write-api
      pool: stable
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: read-api-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: read-api
      pool: stable
