apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqs-access-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.sqsAccessRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-backup-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.dbBackupRoleArn | quote }}
