apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-svc-sqs
  namespace: {{ .Release.Namespace }}
  labels:
    app: worker-svc
spec:
  scaleTargetRef:
    name: worker-svc-burst
  pollingInterval: 2
  cooldownPeriod: 180
  minReplicaCount: 0
  maxReplicaCount: 39
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 30
            - type: Pods
              value: 10
              periodSeconds: 30
          selectPolicy: Max
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-worker-sqs-aws
      metadata:
        awsRegion: {{ .Values.config.awsRegion }}
        queueURLFromEnv: SQS_QUEUE_URL
        # queueLength > 파드 하나당 동시에 들고 있을 목표 메시지 수
        # desired = ceil((visible + inFlight) / queueLength)
        queueLength: "30"
        # activationQueueLength > 파드가 스케일 업하기 시작하는 메시지 수
        activationQueueLength: "0"
        # scaleOnInFlight > 현재 파드 내에서 처리 중인 메시지 수를 고려하여 스케일링 여부 결정
        scaleOnInFlight: "true"
