{{- if .Values.cloudwatchExporter.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cloudwatchExporter.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.cloudwatchExporter.roleArn | quote }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
{{- end }}
