{{- if .Values.cloudwatchExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: cloudwatch-exporter
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: cloudwatch-exporter
  ports:
    - name: metrics
      port: {{ .Values.cloudwatchExporter.port }}
      targetPort: metrics
{{- end }}
