{{- if and .Values.redisExporter.enabled .Values.redisExporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
    {{- with .Values.redisExporter.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: redis-exporter
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.redisExporter.serviceMonitor.interval }}
      path: /metrics
{{- end }}
